---
- name: first playbook
  hosts: all
  become: true
  tasks:
    - name: Download Long Term Jenkins release
      get_url:
        validate_certs: false
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        validate_certs: false
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: yum update
      yum:
        name: "*"
        state: latest
    - name: install java
      yum:
        name: java-devel
        state: latest

    - name: Install jenkins
      yum:
        name: jenkins
        state: latest

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
